# File: .jreleaser/config.yml

# Konfigurasi proyek dasar
project:
  # Pola untuk menghitung versi otomatis
  version:
    pattern: v{{projectVersion}}

# Konfigurasi untuk rilis di GitHub
release:
  github:
    # Mengaktifkan fitur update (commit balik CHANGELOG.md & pom.xml)
    update:
      enabled: true
    # Menggunakan file untuk catatan rilis naratif
    releaseNotes:
      file: RELEASE_NOTES.md
    # Mengaktifkan pembacaan judul Isu & PR
    issues:
      enabled: true

# Konfigurasi untuk Changelog
changelog:
  preset: conventional-commits
  formatted: ALWAYS
  file: CHANGELOG.md
  replacers:
    - search: '#([0-9]+)'
      replace: '[#$1]({{repoHost}}/{{repoOwner}}/{{repoName}}/issues/$1)'

# Konfigurasi untuk file artefak yang akan diunggah
files:
  artifacts:
    - path: 'target/{{projectArtifactId}}-{{projectVersion}}.jar'
      name: {{projectArtifactId}}-{{projectVersion}}.jar