name: Create Stable Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Bump version and create release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install semantic-release dependencies
        run: |
          npm install -g semantic-release @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/changelog @semantic-release/github @semantic-release/git semantic-release-maven

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      # Langkah 1: Jalankan semantic-release dalam mode "dry-run" untuk mendapatkan versi berikutnya
      - name: Get next version
        id: get_version
        run: |
          npx semantic-release --dry-run > release_output.txt
          VERSION=$(grep 'The next release version is' release_output.txt | sed -E 's/.* ([0-9]+\.[0-9]+\.[0-9]+).*/\1/')
          if [ -z "$VERSION" ]; then
            echo "No new version to release. Exiting."
            echo "NO_RELEASE=true" >> $GITHUB_ENV
          else
            echo "Next version is $VERSION"
            echo "VERSION=$VERSION" >> $GITHUB_ENV
          fi

      # Langkah 2: Build, rename, dan buat checksum HANYA jika ada versi baru
      - name: Prepare Release Assets
        if: env.NO_RELEASE != 'true'
        run: |
          # Build the application
          mvn -B package -DskipTests

          # Create a directory for release assets
          mkdir -p target/release-assets

          # Find the JAR file (assuming one JAR is built in target)
          JAR_FILE=$(find target -maxdepth 1 -name "*.jar")
          if [ ! -f "$JAR_FILE" ]; then
            echo "JAR file not found!"
            exit 1
          fi

          # Generate dynamic parts for the name
          RELEASE_DATE=$(date +'%Y%m%d')
          SHORT_COMMIT=$(git rev-parse --short HEAD)
          
          # Determine asset name based on release type (patch/minor vs major)
          # Default to detailed name for patch/minor
          ASSET_NAME="app-v${VERSION}-${RELEASE_DATE}-${SHORT_COMMIT}"
          # If it's a major/minor version (e.g., x.y.0), use a simpler name
          if [[ "${VERSION}" == *.0 ]]; then
            ASSET_NAME="app-v${VERSION}"
          fi

          # Rename and move assets
          mv "$JAR_FILE" "target/release-assets/${ASSET_NAME}.jar"
          echo "Renamed JAR to ${ASSET_NAME}.jar"

          # Generate checksum for the renamed file
          cd target/release-assets
          sha256sum "${ASSET_NAME}.jar" > "${ASSET_NAME}.jar.sha256"
          echo "Generated checksum file ${ASSET_NAME}.jar.sha256"
          cd ../..

      # Langkah 3: Jalankan semantic-release untuk mempublikasikan
      - name: Run semantic-release
        id: semantic
        if: env.NO_RELEASE != 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release