name: Create Stable Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Bump version and create release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install semantic-release dependencies
        run: |
          npm install -g semantic-release @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/changelog @semantic-release/github @semantic-release/git conventional-changelog-conventionalcommits

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Get next version
        id: get_version
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npx semantic-release --dry-run > release_output.txt || true
          VERSION=$(grep 'The next release version is' release_output.txt | sed -E 's/.* ([0-9]+\.[0-9]+\.[0-9]+).*/\1/')
          if [ -z "$VERSION" ]; then
            echo "No new version to release. Exiting."
            echo "NO_RELEASE=true" >> $GITHUB_ENV
          else
            echo "Next version is $VERSION"
            echo "VERSION=$VERSION" >> $GITHUB_ENV
          fi

      # --- LANGKAH BARU UNTUK MENGGANTIKAN PLUGIN MAVEN ---
      - name: Update pom.xml version
        if: env.NO_RELEASE != 'true'
        run: mvn versions:set -DnewVersion=${{ env.VERSION }} -DprocessAllModules

      - name: Prepare Release Assets
        if: env.NO_RELEASE != 'true'
        run: |
          mvn -B package -DskipTests
          mkdir -p target/release-assets
          JAR_FILE=$(find target -maxdepth 1 -name "*.jar")
          if [ ! -f "$JAR_FILE" ]; then
            echo "JAR file not found!"
            exit 1
          fi
          RELEASE_DATE=$(date +'%Y%m%d')
          SHORT_COMMIT=$(git rev-parse --short HEAD)
          ASSET_NAME="app-v${VERSION}-${RELEASE_DATE}-${SHORT_COMMIT}"
          if [[ "${VERSION}" == *.0 ]]; then
            ASSET_NAME="app-v${VERSION}"
          fi
          mv "$JAR_FILE" "target/release-assets/${ASSET_NAME}.jar"
          cd target/release-assets
          sha256sum "${ASSET_NAME}.jar" > "${ASSET_NAME}.jar.sha256"
          cd ../..

      - name: Run semantic-release
        id: semantic
        if: env.NO_RELEASE != 'true'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
